all:
  version: 0.2.0

  autologin_expiration: 84600

  notification:
    missing_bookings: true

  user:
    cultures: [de,en]


  system:
    email:
      host: "servicemail.rotex.de"
      authentification: true
      port: 25
      username:
      password:
      from: "timo.haberkern@rotex.de"