all:
  version: 0.8.0

  autologin_expiration: 84600

  notification:
    missing_bookings: true

  user:
    cultures: [de,en]

  system:
    email:
      host: "servicemail.rotex.de"
      authentification: true
      port: 25
      username:
      password:
      from: "timo.haberkern@rotex.de"

dev:
  frontend_url: http://timeboxx_ng.local/frontend_dev.php

prod:
  frontend_url: http://timeboxx_ng.local