---
Account:
  tableName: tb_account
  columns:
    type: { type: enum, values: [free, small, pro, unlimited] }
    valid_until: { type: date }
    name: { type: string(100) }
  actAs:
    Timestampable: ~
    
User:
  tableName: tb_user
  columns:
    first_name: { type: string(255) }
    last_name: { type: string(255) }
    email: { type: string(255) }
    account_id: { type: integer(20) }
    username: { type: string(255) }
    password: { type: string(255) }
    administrator: { type: boolean }
    locked: { type: boolean }
  relations:
    Account: { class: Account, foreignAlias: users, local: account_id }
  actAs:
    Timestampable: ~
    
TimeLogItem:
  tableName: tb_timelog_item
  columns:
    value: { type: double }
    itemdate: { type: date }
    type_id: { type: integer(20) }
    project_id: { type: integer(20) }
    user_id: { type: integer(20) }
    note: { type: clob }
  relations:
    TimeItemType: { class: TimeItemType, local: type_id }
    User: { class: User, local: user_id, foreignAlias: TimeLogItems }
    Project: { class: Project, local: project_id, foreignAlias: TimeLogItems }
  actAs:
    Timestampable: ~

MissingTimeItemEntry:
  tableName: tb_missing_time_entries
  columns:
    day: { type: date }
    user_id: { type: integer(20) }
    ignored_at: { type: timestamp }
  relations:
    User: { class: User, foreignAlias: MissingTimeItemEntries, local: user_id }

TimeItemType:
  tableName: tb_timeitem_type
  columns:
    name: { type: string(255) }
    account_id: { type: integer(20) }
  relations:
    Account: { class: Account, foreignAlias: TimeItemTypes, local: account_id }    

Project:
  tableName: tb_project
  columns:
    name: { type: string(255) }
    number: { type: string(100) }
    owner_id: { type: integer(20) }
    account_id: { type: integer(20) }
  relations:
    Owner: { class: User, foreignAlias: OwnedProjects, local: owner_id }
    AssignedUser: { class: User, refClass: ProjectUser }
    Account: { class: Account, foreignAlias: Projects, local: account_id }
    
ProjectUser:
  tableName: tb_project_user
  columns:
    project_id: { type: integer(20) }
    user_id: { type: integer(20) }

Setting:
  tableName: tb_settings
  columns:
    user_id: { type: integer(20) }
    culture: { type: string(10) }
    reminder: { type: boolean }
    theme: { type: string(255), default: 'default' }
  relations:
    User: { class: User, local: user_id, foreignType: one }

Token:
  tableName: tb_token
  columns:
    user_id: { type: integer(20) }
    action:
      type: enum
      values: [autologin, recovery]
    value: { type: string(255) }
  relations:
    User: { foreignAlias: Tokens, class: User, local: user_id }
  actAs:
    Timestampable: ~